// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var WordCount_test = 0;

var WordCount = 0;

exports.WordCount_test = WordCount_test;
exports.WordCount = WordCount;
/* No side effect */
