// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var SpaceAge_test = 0;

var SpaceAge = 0;

exports.SpaceAge_test = SpaceAge_test;
exports.SpaceAge = SpaceAge;
/* No side effect */
