// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function hasFactor(x, y) {
  return Caml_int32.mod_(x, y) === 0;
}

function isLeapYear(year) {
  var match = hasFactor(year, 4);
  if (match && (hasFactor(year, 400) || !hasFactor(year, 100))) {
    return true;
  } else {
    return false;
  }
}

exports.isLeapYear = isLeapYear;
/* No side effect */
