// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function hasFactor(x, y) {
  return Caml_int32.mod_(x, y) === 0;
}

function isLeapYear(year) {
  if (hasFactor(year, 4)) {
    if (hasFactor(year, 100)) {
      return hasFactor(year, 400);
    } else {
      return true;
    }
  } else {
    return false;
  }
}

exports.isLeapYear = isLeapYear;
/* No side effect */
