// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


function ageOn(planet, secs) {
  var ratio;
  switch (planet) {
    case 0 : 
        ratio = 0.2408467;
        break;
    case 1 : 
        ratio = 0.61519726;
        break;
    case 2 : 
        ratio = 1.0;
        break;
    case 3 : 
        ratio = 1.8808158;
        break;
    case 4 : 
        ratio = 11.862615;
        break;
    case 5 : 
        ratio = 29.447498;
        break;
    case 6 : 
        ratio = 164.79132;
        break;
    case 7 : 
        ratio = 84.016846;
        break;
    
  }
  return secs / 31557600 / ratio;
}

exports.ageOn = ageOn;
/* No side effect */
