// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var RnaTranscription_test = 0;

var RnaTranscription = 0;

exports.RnaTranscription_test = RnaTranscription_test;
exports.RnaTranscription = RnaTranscription;
/* No side effect */
