// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var Raindrops_test = 0;

var Raindrops = 0;

exports.Raindrops_test = Raindrops_test;
exports.Raindrops = Raindrops;
/* No side effect */
