// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");

function wordCount(phrase) {
  return List.fold_left((function (dict, x) {
                var match = dict[x];
                if (match !== undefined) {
                  dict[x] = match + 1 | 0;
                  return dict;
                } else {
                  dict[x] = 1;
                  return dict;
                }
              }), { }, List.map((function (x) {
                    return x.replace((/[\.:&^!#@$%]/g), "").toLowerCase();
                  }), List.filter((function (x) {
                          return x.trim() !== "";
                        }))($$Array.to_list(phrase.split((/,|'\s|\s'|\s/))))));
}

exports.wordCount = wordCount;
/* No side effect */
